apiVersion: v1
data:
  DB_HOST: mariadb
  DB_NAME: test
  DB_PORT: "3306"
  DB_PWD: TestDB@home2
  DB_USER: root
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_PASS: TestDB@home2
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: nodewithdb-nodeapp-docker-node-env
  name: nodeapp-docker-node-env
