apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ./../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ./../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - args:
        - sh
        - -c
        - redis-server
        - --requirepass
        - ${REDIS_PASS}
        env:
        - name: REDIS_PASS
          valueFrom:
            configMapKeyRef:
              key: REDIS_PASS
              name: redis-docker-redis-env
        image: redis
        imagePullPolicy: ""
        name: rediscont
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
