# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- nodewithdb-deployment.yaml

# labels added to all Resources
commonLabels:
  environment: dev

# annotations added to all resources
commonAnnotations:
  support: self-service
