apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql2-docker-compose-env
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS test;
    USE `test`;
    CREATE TABLE IF NOT EXISTS `test`.`test` (`id` serial,`name` varchar(50) NOT NULL, PRIMARY KEY (id));
    insert into test (`name`) VALUES ('USA'),('Bolivia'),('Chile'),('Colombia'),('India');
