apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ./../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nodewithdb
  name: nodewithdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodewithdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ./../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nodewithdb
    spec:
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: nodeapp-docker-node-env
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: nodeapp-docker-node-env
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: nodeapp-docker-node-env
        - name: DB_PWD
          valueFrom:
            configMapKeyRef:
              key: DB_PWD
              name: nodeapp-docker-node-env
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: nodeapp-docker-node-env
        image: bolbeck/nodewithdb
        imagePullPolicy: ""
        name: nodewithdbcont
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
